### ISSUE TITLE
Working demo

### ISSUE THREAD

**Issue by jasperdg** [Gungz/flux-bot#1]
We're awaiting Twitter development account approval. Could you setup this demo for us to test out? We'd like to play around with it before we make out final decission.

**Comment by Gungz** [comment]
Hi @jasperdg, sorry for late reply, I still have the Bot running against my local, as I am still working, I am unable yet to deploy the webhook to public server. Pls try @BotHackathon "will x happen by y?" 02-02-2021 10:25pm --> please pay attention on the format to include the double-quote and the date until time when you test.

**Comment by Gungz** [comment]
@jasperdg, Please follow the bot in Twitter before you try it, if I remember correctly it won't work if the bot is not followed.
